version: '3.9'

services:
  back:
    build:
      context: ./back
    container_name: bobapp-back10
    ports:
      - "8081:8080"
    networks:
      - bob-network

  front:
    build:
      context: ./front
    container_name: front10-container
    ports:
      - "4200:80"
    depends_on:
      - back
    networks:
      - bob-network

networks:
  bob-network:
    driver: bridge
